### ISSUE TITLE
Can not override page.st in src/main/paradox/_template

### ISSUE THREAD

**Issue by zoosky** [lightbend/paradox#101]
While css overriding works in `src/main/paradox/_template/css`, it seems not to work for `src/main/paradox/_template/page.st`

Paradox com.lightbend.paradox:paradox-theme-generic:0.2.9

**Comment by JohnMurray** [comment]
I have also attempted to modify the `page.st` and `title.st` templates to no avail.

**Comment by pvlugter** [comment]
I expect this was fixed in #108? There's also a test for overriding the page.st in the generic template. Available in paradox 0.2.11.

**Comment by metasim** [comment]
I was able to do this with this tip provided by @jonas 

https://github.com/lightbend/paradox/issues/139#issuecomment-326136971

**Comment by zoosky** [comment]
I tested with 0.3.0 and it works for me. :+1:  Thanks.
