### ISSUE TITLE
Text switching

### ISSUE THREAD

**Issue by raboof** [lightbend/paradox#106]
Beyond switching tab groups (good to see #95!), it would be interesting to allow switching some of the 'regular text' along with it: the Akka and akka-http documentation refers to types a lot, and these can look different or even _be_ completely different between the Java API and the Scala API.

We'd have to come up with some (hopefully reasonably lightweight) syntax - I'm not aware of any conventions to add this kind of markup to a Markdown document?

**Comment by pvlugter** [comment]
Fixed in #107
