### ISSUE TITLE
Check anchor targets in @ref directive

### ISSUE THREAD

**Issue by pvlugter** [lightbend/paradox#120]
`@ref` already checks for valid page references. It also allows targets to be specified with `@ref:[page](page.md#target)`. It would be useful if it also checked that the target is a valid anchor in that page. Particularly as a heading could be updated without realising there are links to it.

A bigger question: should we even have explicit `@ref`s? Paradox could also check the validity of all relative links, and transform source md links to output html links automatically. And optionally check external links exist.

**Comment by jonas** [comment]
Related to #53
