### ISSUE TITLE
Make sure @fiddle degrades nicely if no internet or scalafiddle down

### ISSUE THREAD

**Issue by ktoso** [lightbend/paradox#122]
We should make sure docs remain useful if someone wants to browse them on an airplane or fiddle is down. This is likely as simple as making sure that if the fiddle js does not trigger, the code is still visible as normal code snippet.

**Comment by ktoso** [comment]
This is likely as simple as "start by being a snippet, but add a callback to hide the snippet once the scalafiddle iframe has loaded" - that we likely can do by adding an onload in the iframe.

**Comment by ktoso** [comment]
cc @andreaTP

**Comment by andreaTP** [comment]
Should be fixed with: https://github.com/lightbend/paradox/pull/231
