### ISSUE TITLE
ScalaFiddle should not execute on page load

### ISSUE THREAD

**Issue by ktoso** [lightbend/paradox#123]
When the page loads, we immediately execute the scalafiddle snippet (see example here http://doc.akka.io/docs/akka/current/scala/actors.html#here-is-another-example-that-you-can-edit-and-run-in-the-browser- ).

In order to avoid heating CPUs when people are not really interested in running the example, we should just load the fiddle, but not run it - people can run it if they want to using the run button after all.

// cc @andreaTP @ochrons

**Comment by ochrons** [comment]
Currently there's no option in embedded scalafiddle to prevent compilation and execution of the fiddle after loading, but I can add one, since it seems useful in other contextes as well 😄

**Comment by andreaTP** [comment]
@ochrons even a different way to load fiddles other than an `iframe` could be explored maybe...

**Comment by ochrons** [comment]
I already implemented and deployed a "passive" mode which allows you to control whether anything is compiled/run at load time. For example `https://embed.scalafiddle.io/embed?sfid=FxfEK7C/2&passive` prevents compilation.

**Comment by ktoso** [comment]
Very cool, thanks for being so responsive - should we assume that option will work and work it into paradox already or give it some time to stabilize? :)

**Comment by ochrons** [comment]
It works fine and was trivial to implement :) The only "issue" with any of these changes is that ScalaFiddle has very aggressive caching, so sometimes these changes do not propagate to users' browsers until a few hours later.

**Comment by andreaTP** [comment]
I'm already working on the "two steps" loading for offline, but I cannot be as responsive as @ochrons in these days :-) I can integrate this mode in next PR (hopefully until the end of next week)

**Comment by patriknw** [comment]
Any update here? Would be nice to get rid of the blocking when loading the Akka doc pages.

**Comment by andreaTP** [comment]
Hi @patriknw , to be honest I was working on this: https://github.com/andreaTP/paradox/tree/fiddleFallback

but I felt uncomfortable with the implementation, since it looks like that, to have a reliable way to catch errors on the `iframe` load we have to inject too much javascript.

I paused to work on that, but feel free to suggest a different approach or to take over what I started...

**Comment by patriknw** [comment]
I don't know how but I would prefer that it only shows the code when page is loaded and then compilation and run starts when clicking the > button

**Comment by raboof** [comment]
This has now been fixed using the `&passive` feature, right? E.g. at http://doc.akka.io/docs/akka/current/scala/actors.html#defining-an-actor-class

**Comment by ktoso** [comment]
Yes though I'd argue it we should attach this param by default

**Comment by patriknw** [comment]
yeah, compiling/running on page load is pretty harmful to the user experience if incorporated in docs

**Comment by andreaTP** [comment]
We can close as fixed in: https://github.com/lightbend/paradox/pull/231
