### ISSUE TITLE
Cross Build for SBT 1.0.0

### ISSUE THREAD

**Issue by swachter** [lightbend/paradox#134]

**Comment by bantonsson** [comment]
This depends on sbt/sbt-web#157

**Comment by benmccann** [comment]
sbt-web 1.4.2 has been released with support for sbt 1.0.0

**Comment by larsrh** [comment]
See also #132. Porting to latest sbt-web will take some effort. (Also note the circular dependency in the build.)

**Comment by ktoso** [comment]
https://github.com/sbt/sbt-web/issues/157 was done, might be a good time to try to do this... 
I may get to it this week, as we'd like to be able to build Akka on 1.0.1 sbt hm...

**Comment by bantonsson** [comment]
@ktoso I started looking at this briefly before I got tied up with other things. I'll try ro get it unstuck, , since we would like to move to sbt 1.0.x as well.

**Comment by ktoso** [comment]
Cool, I'm not attacking this for now, let me know if you would :)

**Comment by pvlugter** [comment]
Published paradox `0.3.0` with the cross build.
