### ISSUE TITLE
exteref tag issue inside group tabs

### ISSUE THREAD

**Issue by rsoletob** [lightbend/paradox#135]
Hi all, 

We have an unexpected behaviour using @exteref inside group tabs:

Code example:

```md
### TITLE

@var[env_var_1]
:   @extref[ref1](ref:)

@var[env_var_2]
:   @extref[ref2](ref:)

@var[env_var_3]
:   @extref[ref3](ref:)

```

Expected:

![expected](https://user-images.githubusercontent.com/16651478/29447238-385df156-83f1-11e7-8982-f7b8988770c4.png)

(with hyperlinks)

Result:

![current](https://user-images.githubusercontent.com/16651478/29447237-385b8858-83f1-11e7-93c1-dc615fc22f15.png)

Can this be done? Thank you in advance.

Scala version: 2.12.2
sbt: 0.13.15
Paradox version: 0.2.13
sbt-site: 1.2.1

**Comment by jonas** [comment]
Definition lists are only converted to tabs when they contain code. One option is to copy [the related code](https://github.com/lightbend/paradox/blob/2b47d89f56a5b5c74d59884bff0abe4480ae7c0a/themes/generic/src/main/assets/js/groups.js#L49-L71) and include it via a custom theme file so it works for all definition lists .

**Comment by rsoletob** [comment]
Thanks you for your explanation @jonas , I close this issue then.
