### ISSUE TITLE
`@@@index` ToC does not include grouped page content

### ISSUE THREAD

**Issue by jonas** [lightbend/paradox#137]
In Akka HTTP, we are consolidating the Java and Scala documentation (akka/akka-http#1290) and I've noticed that the section overviews, which I believe is generated using the `@@@index` feature, does not include content in a page that have been grouped for example with

```
@@@ div { .group-java }
```

Some screenshots of JSON support:
<img width="777" alt="screen shot 2017-08-29 at 9 00 42 am" src="https://user-images.githubusercontent.com/8417/29822322-06370284-8c99-11e7-9c6b-eb2429264708.png">
<img width="807" alt="screen shot 2017-08-29 at 9 00 51 am" src="https://user-images.githubusercontent.com/8417/29822332-1244d362-8c99-11e7-8ea8-17d695dcefeb.png">

Before doc consolidation it was like [this](http://doc.akka.io/docs/akka-http/10.0.9/java/http/common/index.html):
<img width="776" alt="screen shot 2017-08-29 at 9 04 50 am" src="https://user-images.githubusercontent.com/8417/29822363-30837392-8c99-11e7-8f98-0d8d8162b592.png">

**Comment by raboof** [comment]
Hmm, I wonder if this happens for any headings that are inside a `@@@ div` rather than at the 'top level'?

**Comment by jonas** [comment]
Fixed by #170
