### ISSUE TITLE
Provide documentation on fiddle directive

### ISSUE THREAD

**Issue by metasim** [lightbend/paradox#141]
Having a minimal example of `fiddle [here](http://developer.lightbend.com/docs/paradox/latest/) would be great to learn its usage. I see there's something in the [0.2.1 release notes](https://github.com/lightbend/paradox/blob/790f97285fd012acb4a91fe70c4d243831e91d21/notes/0.2.1.markdown#scalafiddle-integration), but something more formal would be helpful.

**Comment by andreaTP** [comment]
yes, we should improve the documentation, but let's first have a feedback from: https://github.com/lightbend/paradox/issues/124
