### ISSUE TITLE
Hide line support in @snip directive

### ISSUE THREAD

**Issue by 2m** [lightbend/paradox#157]
The old sphinx doc tool-chain in akka-http [supported hiding arbitrary code lines](https://github.com/akka/akka/blob/v2.5.1/akka-docs/_sphinx/exts/includecode2.py#L75) from inclusion in the snippets by adding a `// hide` to the end of the line. This is now lacking in the current `@snip` directive. Instead current akka-http docs contain `// hide` comments in some of the pages, like [this one](https://doc.akka.io/docs/akka-http/10.0.10/scala/http/routing-dsl/case-class-extraction.html).

There are 18 such comments in the akka-http docs currently.
<details><pre>
docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala:                complete("") // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:          null // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:    Get("/color?red=1&green=2&blue=3") ~> route ~> check { responseAs[String] shouldEqual "Color(1,2,3)" } // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:          null // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:    Get("/color?red=1&green=2&blue=3") ~> route ~> check { responseAs[String] shouldEqual "Color(1,2,3)" } // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:          null // hide
docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala:    Get("/color/abc?r=1&g=2&b=3") ~> route ~> check { responseAs[String] shouldEqual "Color(abc,1,2,3)" } // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala:    verify(route) // hide
docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala:        null // hide
docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala:      null // hide
docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala:      null // hide
</pre></details>

**Comment by bantonsson** [comment]
This is available if you write `// #hide` instead, but maybe you wan't to join the discussion in #149

**Comment by 2m** [comment]
Roger. Fixed the issue in akka-http: https://github.com/akka/akka-http/pull/1457
