### ISSUE TITLE
Make sure tech-hub publishes from this lightbend/paradox repo

### ISSUE THREAD

**Issue by ktoso** [lightbend/paradox#164]
Make sure this thing http://developer.lightbend.com/docs/paradox/latest/ actually picks the right version.

cc @2m @eed3si9n

**Comment by 2m** [comment]
What was wrong with it?

**Comment by ktoso** [comment]
We moved repo, so this is about making sure all references are fine — that
tech hub still works like it should now regarding this repo.

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On October 23, 2017 at 17:49:04, Martynas Mickevičius (
notifications@github.com) wrote:

What was wrong with it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lightbend/paradox/issues/164#issuecomment-338590447>,
or mute the thread

**Comment by 2m** [comment]
Ahh. This repo was not moved. We moved config. :)

**Comment by ktoso** [comment]
Ah right all good then; was mass-looking-over all repositories and forgot this was always here :)
