### ISSUE TITLE
Custom properties lookup doesn't work for link URL

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/paradox#178]
## steps

in `build.sbt`:

```scala
    paradoxProperties in Paradox ++= Map(
      "foo" -> "bar"
    )
```

in `x.md`:

```
- $foo$
- [foo]($foo$)
- [foo][foo1]

 [foo1]: $foo$
```

## problem

```html
<ul>
  <li>
  <p>bar</p></li>
  <li><a href="$foo$">foo</a></li>
  <li><a href="$foo$">foo</a></li>
</ul>
```

## expectation

`$foo$` expands to `bar`.

**Comment by jonas** [comment]
The setting must be scoped: `paradoxProperties in Compile`.

**Comment by eed3si9n** [comment]
In my actual build it's scoped to `Paradox` configuration since I am using sbt-site. (I updated the above **steps**).

The first bullet point is substituted to `<p>bar</p>`, so the general mechanism I think is hooked up. It's just that it doesn't seem to work in the URL position.

**Comment by deanwampler** [comment]
Still broken:

```
@@@ index

* [README](readme/index.md)
* [Release Notes](release-notes/@var[fdp.platform]/index.md)  <-- boom!
```
