### ISSUE TITLE
Improve ScalaFiddle integration

### ISSUE THREAD

**Issue by ochrons** [lightbend/paradox#179]
ScalaFiddle now comes with its own integration system, which makes it easy to convert source code blocks in Markdown into ScalaFiddles. See https://github.com/scalafiddle/scalafiddle-core/tree/master/integrations

There are plugins for Jekyll and Github, too, providing examples on how to do the integration within a documentation build system.

**Comment by 2m** [comment]
It might be a good idea to create a custom paradox directive for the improved ScalaFiddle integration and package it up as a separate project.

**Comment by ennru** [comment]
Fixed with #231
