### ISSUE TITLE
Duplicates in Java snippet rendering

### ISSUE THREAD

**Issue by johanandren** [lightbend/paradox#181]
Discovered in Alpakka: akka/alpakka#721

**Comment by jonas** [comment]
Looking at the [Transactionally receiving javax.jms.Messages from a JMS provider](https://github.com/akka/alpakka/blob/master/docs/src/main/paradox/jms.md#transactionally-receiving-extrefjavaxjmsmessages-from-a-jms-provider) section which has duplicates I see duplicate use of the `create-jms-source` label.

 - https://github.com/akka/alpakka/blob/a24bbb40f246ab61cd5be34527429c8991de88f1/jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java#L299-L305
- https://github.com/akka/alpakka/blob/a24bbb40f246ab61cd5be34527429c8991de88f1/jms/src/test/java/akka/stream/alpakka/jms/javadsl/JmsConnectorsTest.java#L354-L360

Similarly the `run-jms-source` occurs two times. This would explain the duplicates for at least those two cases.

**Comment by johanandren** [comment]
Argh, I must have missed that somehow.
