### ISSUE TITLE
Nested WrapDirective's

### ISSUE THREAD

**Issue by raboof** [lightbend/paradox#185]
It seems it is not possible to nest `WrapDirective`s. Is that a restriction of the pegdown parser or something we might be able to make possible?

**Comment by jrudolph** [comment]
I think it might be that the parser is too strict when parsing container block directive content.

**Comment by jrudolph** [comment]
I had a quick look into it but it doesn't seem easy to do. When the parser sees a starting `@@@ xys` it basically skims over the next text until it finds the next ending `@@@` and then recursively parses the contents afterwards. What we would have to do is to correspond matching pairs in the parser.

**Comment by 2m** [comment]
Fixed in https://github.com/lightbend/paradox/pull/188
