### ISSUE TITLE
Include (sections from) other .md files

### ISSUE THREAD

**Issue by raboof** [lightbend/paradox#195]
It might be nice have an 'include' directive that pulls in content from another .md file - perhaps even one outside the paradox sources, to be able to pull in a fragment that is also in the README.md

**Comment by jroper** [comment]
Implemented in #281, and pulling in outside paradox sources is supported in the same way it is for snips, you can pass in and use base dir properties, so you should be able to pull in `README.md` using `$root$/README.md`. It also supports sections using exactly the same syntax as snips, in markdown you would include the section marker using a Markdown comment, ie `<!--- #my-section --->`.
