### ISSUE TITLE
Provide in-line directive for linking to ScalaDoc

### ISSUE THREAD

**Issue by ktoso** [lightbend/paradox#2]
Would need to be aware of which version it is, and where scaladoc is located.

**Comment by pvlugter** [comment]
Slick documentation could be a good inspiration, with ScalaDoc linking for Sphinx:

https://github.com/slick/slick/blob/master/slick/src/sphinx/exts/apilinks.py

And link checker:

https://github.com/typesafehub/sbt-sdlc

**Comment by jonas** [comment]
@ktoso What about linking to javadoc? See discussion in #27

**Comment by jonas** [comment]
This can be closed now.
