### ISSUE TITLE
Latest version is 0.3.3, but 0.3.2 is latest on releases page

### ISSUE THREAD

**Issue by wsargent** [lightbend/paradox#205]
https://github.com/lightbend/paradox/releases vs http://mvnrepository.com/artifact/com.lightbend.paradox/paradox

The documentation is also showing 0.3.2, not 0.3.3: https://developer.lightbend.com/docs/paradox/current/

**Comment by bantonsson** [comment]
Seems like the v0.3.3 release by @raboof was incomplete. I just added the v0.3.3 tag to the right commit, but I don't know what went in to the release.

**Comment by 2m** [comment]
We would like to release 0.3.4 soon (today/tomorrow) with the changes needed to Alpakka. So after the release we will not have to continue the search for 0.3.3. :)

**Comment by 2m** [comment]
Releasing 0.3.4 today.

**Comment by wsargent** [comment]
woo-hoo!

**Comment by 2m** [comment]
`0.3.4` is in Maven Central, but it contains a regression: https://github.com/lightbend/paradox/pull/212

`0.3.5` will follow soon.
