### ISSUE TITLE
Allow usage of the absolute path to files when includding snippets

### ISSUE THREAD

**Issue by 2m** [lightbend/paradox#209]
Currently when including snippets absolute path works the same way as relative paths. Both of the following will have the same result:

```
@@snip [snip](/reference/src/test/scala/docs/scaladsl/ReferenceSpec.scala) { #source }

@@snip [snip](reference/src/test/scala/docs/scaladsl/ReferenceSpec.scala) { #source }
```

which will lookup source file relative to the `paradox/sourceDirectory` setting value.

It would be great to have absolute path support which would lookup snippet files relative to the root of the repository. This would enable snippet linking from the Github UI as well.

**Comment by raboof** [comment]
That sounds great!
