### ISSUE TITLE
@@snip: support multiple sections

### ISSUE THREAD

**Issue by jonas** [lightbend/paradox#21]
In the Akka docs a lot of snippets refer to multiple sections, e.g. to list imports along with the code, either using multiple labels:
```rst
.. includecode:: code/docs/actorlambda/MyActor.java
   :include: imports,my-actor
```

or by using the same label multiple times:
```scala
//#example
import a.A
//#example

object B {
  //#example
  def b(a: A): Int = ???
  //#example
}
```

For akka/akka-http#1, the second case is more important and currently causes a `block not closed` error.

**Comment by ktoso** [comment]
Hey @dwijnand @eed3si9n @pvlugter,
do you think you could help us out on this one?

We've spread crazy thin the next 3 weeks and this would be something that would allow us to release the first stable Akka HTTP with paradox docs right away. 

(Trying to understand if we need to somehow make time to implement this or if we can count on help while adopting paradox).

**Comment by jonas** [comment]
OK, the second case actually works. The error was caused by space between the marker symbol and the label:
```diff
-    //# path-dsl
+    //#path-dsl
```

**Comment by ktoso** [comment]
Uff, very glad about that :)
We use that a lot, so perhaps we're all good here?

**Comment by jonas** [comment]
I've only managed to convert the `includecode` directives. Will wait to see how conversion of`includecode2` goes.
