### ISSUE TITLE
"Illegal 'Cookie' header" caused by `paradoxGroups`.

### ISSUE THREAD

**Issue by metasim** [lightbend/paradox#220]
It appears that paradox stores a browser cookie to record the selected group state. The format written looks like this:

```
paradoxGroups={"language":"group-scala"}
```

According to the HTTP spec, this is invalid:

> A `<cookie-value>` can optionally be set in double quotes and any US-ASCII characters excluding CTLs, whitespace, double quotes, comma, semicolon, and backslash are allowed. Encoding: Many implementations perform URL encoding on cookie values, however it is not required per the RFC specification. It does help satisfying the requirements about which characters are allowed for `<cookie-value>` though.

(double quotes are not allowed)

~~Furthermore, this cookie is recorded in the global scope, so it ends up being sent to all sites the browser visits.~~

This cookie should be set using valid encodings, ~~and in a domain-restricted scope~~.

**Comment by raboof** [comment]
What browser are you seeing this with? I assumed that it would default to the 'current' domain (e.g. https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie).

Avoiding illegal characters in the cookie string would indeed be good ;).

**Comment by metasim** [comment]
My browser is Google Chrome, 67.0.3396.99 

I only found this problem because the application I'm developing, which uses Akka HTTP (who's header parser is pretty strict), was reporting bad cookies from the browser. The service/application has nothing to do with Paradox, but now I'm realizing that I had been writing docs and viewing the results locally.... so the domain in both cases was `localhost`.... So disregard the scope aspect of this bug.

**Comment by 2m** [comment]
Fixed in https://github.com/lightbend/paradox/pull/222
