### ISSUE TITLE
Mermaid Integration

### ISSUE THREAD

**Issue by wsargent** [lightbend/paradox#223]
I've added mermaid integration to my website using sbt-paradox 0.3.5 and a custom `MermaidDirective`

https://github.com/wsargent/ocaps/pull/17

Example page at https://wsargent.github.io/ocaps/mermaid.html

The only difficulty I have is that I need to use a fenced code block in order to prevent Pegdown from rendering nodes individually.  I'd be happy to submit a PR if there's a `RawDirective` or something that would make this unnecessary.

```
@@@mermaid
\```
graph TD
  A[Christmas] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[Car]
\```
@@@  
```

Thanks @szeiger for ornate [mermaid integration](https://szeiger.github.io/ornate-doc/diagrams.html) and @pvlugter for 0.3.5 custom directives :-)

**Comment by raboof** [comment]
That is pretty cool! We should at the very least link to it from the docs. It seems a bit big to include into paradox itself, but perhaps eventually could be an `sbt-paradox-mermaid` like https://github.com/lightbend/sbt-paradox-apidoc ?

**Comment by wsargent** [comment]
Maybe -- on the other hand, it looks like Scalafiddle works as a leaf directive, and it may be possible to do something with the live editor that works the same way, i.e. for the text

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

you could base-64 and embed the contents of the diagram itself...

https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ

Ornate has a thing where the fenced code blocks each have their own highlighters, so you can just do 

\```mermaid
 A[Christmas] -->|Get money| B(Go shopping)
  B --> C{Let me think}
  C -->|One| D[Laptop]
  C -->|Two| E[iPhone]
  C -->|Three| F[Car]
\```

but I don't think that works in Paradox.

**Comment by 2m** [comment]
scalafiddle integration came before we begun to split functionality to plugins.

\```mermaid support would be really nice to have.

**Comment by ennru** [comment]
Any progress on this, @wsargent?

**Comment by wsargent** [comment]
@ennru this works fine for me -- see https://github.com/wsargent/ocaps/pull/17.

**Comment by ennru** [comment]
I've PRed support for a raw block, which I believe solves your need. Combined with a `@@@div` the CSS class may be set for the block.
So a Paradox plugin for Mermaid may just need to add the appropriate Javascript includes to the templates. Or preferably introduce a new template that must be applied for pages making use of Mermaid graphs.

**Comment by wsargent** [comment]
Okay, I will add this to list -- may be done next weekend

**Comment by tg44** [comment]
Thanks to a hactoberfest contributor its finally on maven central: [sbt-paradox-diagrams](https://index.scala-lang.org/TeamWanari/sbt-paradox-diagrams)

Should/can I add it to the paradox documentation [extensions/directives](https://developer.lightbend.com/docs/paradox/current/customization/extensions.html#directives) section?

**Comment by ennru** [comment]
This is great! Thank you for sharing.
Please open a PR to add it to the Paradox docs.
