### ISSUE TITLE
Code indentation is overindented

### ISSUE THREAD

**Issue by JustinPihony** [lightbend/paradox#228]
This seems to be a result of https://github.com/lightbend/paradox/pull/201 

Take a look at https://developer.lightbend.com/docs/reactive-platform/2.0/setup/setup-sbt.html and the multi-line code snippets - the lines past the first are indented almost out of view.

**Comment by ennru** [comment]
The indentation is picked by looking at the #-mark, move the marker to the correct indentation and it will work out.
