### ISSUE TITLE
support JDK 10

### ISSUE THREAD

**Issue by xuwei-k** [lightbend/paradox#235]
pegdown depends on parboiled, parboiled depends on asm 5.2, asm 5.2 does not work with JDK10 😢 

https://github.com/sirthias/parboiled/blob/04277952b8df3f6b76067c5a456aece721ecc00c/project/Dependencies.scala#L15-L18

related to https://github.com/lightbend/paradox/issues/81

**Comment by xuwei-k** [comment]
https://github.com/sirthias/parboiled/pull/123

**Comment by SethTisue** [comment]
paradox is now green at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk10-integrate-community-build/249/consoleFull :+1:
