### ISSUE TITLE
Maven support or CLI support

### ISSUE THREAD

**Issue by mycaule** [lightbend/paradox#236]
I would like to run paradox using maven build system.

Is there a way to generate the documentation without sbt ?

Maybe some kind of technique similar to http://tpolecat.github.io/tut//standalone.html

**Comment by ktoso** [comment]
I would say we're not planning on working on such support; Paradox is intended for our own libraries and not really as a general purpose docs engine. 

If you'd like to work on it you could contribute this though - interested?

**Comment by mycaule** [comment]
For the moment I don't know, For those who use scala with maven or gradle, CLI could be a good option and it would need the configuration part (themes, paths, ...) to be outside of `build.sbt`.

I would like to use a meta approach like https://www.scala-sbt.org/sbt-site/, and also considering using Java world techniques such as https://maven.apache.org/plugins/maven-site-plugin/ since using `pom.xml` for the build is a constraint in my case.

**Comment by ktoso** [comment]
I'm inclined to not keep the ticket open if we know we won't work on it and there's no voulenteer to look into it. It is not a priority for this tool to support various use cases – it serves first and foremost our own projects, and happens to be open source, but not much more.

**Comment by mycaule** [comment]
Yes you can close this. I found two potential workarounds for those who are reading : 
- use docker to generate docs for complex projects for example [traefik go project with python doc generator](https://github.com/containous/traefik/blob/master/CONTRIBUTING.md#documentation)
- use an [ammonite script](https://github.com/lihaoyi/Ammonite) (it would be great if we could call something like `paradox.generate(outputPath)` in a Scala script instead of of `sbt paradox` (this requires modifying code here)

**Comment by benmccann** [comment]
I looked at creating a Paradox Maven plugin today. The main obstacle to figure out is that Maven generally uses Java whereas this plugin is written in Scala. There'd be two possible approaches:

* Write the plugin in Java. The difficulty where is calling the Paradox code from Java. E.g. `Reader` and `Writer` do not define default constructors as [required for Java interop](https://stackoverflow.com/questions/13059528/instantiate-a-scala-class-from-java-and-use-the-default-parameters-of-the-const). We could make some simple changes like that to Paradox that would make this path far easier. It's probably more work to maintain in the long-run than the next approach however
* Write the plugin in Scala. It'd be really nice to find an example of a Scala Mojo. I see [jsuereth/scala-mojo-support](https://github.com/jsuereth/scala-mojo-support) that's supposed to help with this, but unfortunately it looks outdated. [I think the repo it's published to has been taken down](https://github.com/jsuereth/scala-mojo-support/issues/25) and [it doesn't have Scala 2.12 support](https://github.com/jsuereth/scala-mojo-support/issues/26)

**Comment by TimMoore** [comment]
Thanks, @benmccann. I don't have a strong opinion on which approach is better, but here are some examples of Scala Mojos:

- [Lagom](https://github.com/lagom/lagom/tree/master/dev/maven-plugin/src/main/scala/com/lightbend/lagom/maven) (which has a [custom sbt plugin](https://github.com/lagom/lagom/blob/master/project/SbtMavenPlugin.scala) for generating the plugin descriptor)
- [Akka gRPC](https://github.com/akka/akka-grpc/tree/master/maven-plugin/src/main/scala/akka/grpc/maven) (which also has an [sbt plugin](https://github.com/akka/akka-grpc/blob/master/project/SbtMavenPlugin.scala) adapted from Lagom's)
