### ISSUE TITLE
Add Paradox plugins documentation

### ISSUE THREAD

**Issue by ennru** [lightbend/paradox#237]
Now that new functionality is put in plugins to Paradox, the docs should explain how to build those and list the ones we know of.

**Comment by 2m** [comment]
There is a list of some of the themes and plugins here: https://developer.lightbend.com/docs/paradox/current/customization/extensions.html

**Comment by ennru** [comment]
I'd like to see a short how-to.

**Comment by ennru** [comment]
Added more examples, so I hope everybody can find something to copy from those.
Closing this.
