### ISSUE TITLE
Allow snippets to reference files from project root

### ISSUE THREAD

**Issue by jonas** [lightbend/paradox#24]
For project documentation with deeply nested pages it would be helpful to support referencing files using absolute paths which resolve against for example the project root.

An example from Akka HTTP docs:

```markdown
file: /docs/src/main/paradox/scala/http/common/http-model.md

## Instead of:
@@snip [ModeledCustomHeaderSpec.scala](../../../../../../../akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala) { 

## Use the following:
@@snip [ModeledCustomHeaderSpec.scala](/akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala) { 
```

The root could be configurable via the SBT plugin. The main downside is that links won't be "GitHub friendly".

The alternative is to not nest documentation files inside `src/main/paradox` but instead in for example `/docs/` and example source code somewhere other than `/docs/src/main/scala`.

**Comment by dwijnand** [comment]
Along with not being GitHub friendly, this is not file:// friendly, a use
case that I find very useful.

So I'm inclined to vote against this.

**Comment by ktoso** [comment]
I don't think anyone is browsing these docs on github TBH.
It would be really good to support this from a practical perspective. Calculating the right amount of `../` honestly takes me tens of minutes sometimes when I'm tired and writing docs or moved a file somewhere, a lot of pain came from those `../`.

**Comment by bantonsson** [comment]
We use the GitHub friendly feature in our internal docs that also use paradox, not to mention that I can effortlessly jump from the markdown doc to the snippet doc in my editor (yes emacs does that).

If you think the nesting is too deep, then just redefine the sbt setting `sourceDirectory in paradox := "/path/to/nirvana"`.

**Comment by ktoso** [comment]
> If you think the nesting is too deep, then just redefine the sbt setting sourceDirectory in paradox := "/path/to/nirvana".

Not directly solving it - since we link into multiple different projects, so no common root except `/`. However perhaps it might be simplest and most consistent for us if we define that to `baseDirectory` of root project - WDYT @jonas?
Being explicit that it's `docs/scala/blabla` is fine anyway as easy to follow.

**Comment by jonas** [comment]
I was mainly thinking of the sanity of developers maintaining the Akka HTTP documentation, and completely understand the hesitation to break editors and other tools.

Personally, I like the idea of documentation coexisting with each project. So another possibility would be to see if Paradox files can somehow be moved into each subproject thus make linking easier. This way examples would also naturally be part of the subproject's test code.
