### ISSUE TITLE
github.base_url does not link to a branch

### ISSUE THREAD

**Issue by umbreak** [lightbend/paradox#252]
Having the following `build.sbt`
```scala
...
lazy val root = project
  .in(file("."))
  .enablePlugins(ParadoxPlugin)
  .settings(
    name       := "some",
    paradoxProperties in Compile += ("github.base_url" -> "https://github.com/account_example/nexus/tree/branch_example")
  )
```

The links inside the end of the pages (`The source code for this page can be found here.`) point to https://github.com/account_example/nexus/tree/master instead of the `branch_example`.

**Comment by 2m** [comment]
As the logic around that variable recently changed I added a scripted test that tests your scenario (#253). It seems to work as expected. Are you using the latest paradox?

**Comment by umbreak** [comment]
file `plugins.sbt`:
```scala
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"                % "0.4.2")
```

**Comment by 2m** [comment]
Alright. Then my next guess is: do you set `scmInfo` setting value in your project?

**Comment by umbreak** [comment]
I guess the `scmInfo` settings are being set in the `build.sbt` too, right? If that's the case, I don't have anything else in the build.sbt than what I pasted on the first comment.

**Comment by 2m** [comment]
I see. I am a bit out of ideas here, as the scripted test which has the same settings as your example work properly. Could it be the case that you did not reload sbt project after adding `"github.base_url"` paradox property?

**Comment by umbreak** [comment]
The only difference I see from your test is the `paradoxTheme := None,`. I'm using the `paradox-theme-generic` but that should be fine.
Yes I did `clean`, `cleanFiles`, `reload` many times :)

On my ivy cache I have the paradox jar as follows

```bash
$ md5 paradox_2.12-0.4.2.jar
MD5 (paradox_2.12-0.4.2.jar) = cea51a98192f211f44127d9ed531dcac
```

**Comment by jonas** [comment]
@2m I took a closer look. The repo in question is this one https://github.com/umbreak/nexus I believe. #253 tests that the `Full source at GitHub` snippet links use `github.base_url` whereas this issue is about `The source code for this page can be found here` which indeed always links to `.../tree/master`:

https://github.com/lightbend/paradox/blob/master/core/src/main/scala/com/lightbend/paradox/ParadoxProcessor.scala#L159-L173

**Comment by 2m** [comment]
Ahh, of course! I looked at the wrong link...

**Comment by 2m** [comment]
Updated #253 to actually fix the problem reported here.
