### ISSUE TITLE
Something went wrong when releasing 0.5.2

### ISSUE THREAD

**Issue by ennru** [lightbend/paradox#294]
```
[info] 	published paradox_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/lightbend/paradox/paradox_2.12/0.5.2/paradox_2.12-0.5.2-javadoc.jar

...

[info] 	published sbt-paradox to https://oss.sonatype.org/content/repositories/snapshots/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.5.2+0-575e713f+20190308-1553-SNAPSHOT/sbt-paradox-0.5.2+0-575e713f+20190308-1553-SNAPSHOT.pom
```

https://travis-ci.org/lightbend/paradox/builds/503662014#L669

**Comment by raboof** [comment]
Looks like something caused the working directory to be dirty?

**Comment by ennru** [comment]
Ah, yes good clue.

**Comment by 2m** [comment]
Released was borked because of header update during the release.

Missing artifacts released manually, and added a check in Travis PR validation to check for misformated headers: https://github.com/lightbend/paradox/pull/296
