### ISSUE TITLE
Wrong character encoding when running on Windows

### ISSUE THREAD

**Issue by rpiaggio** [lightbend/paradox#306]
When running on Windows, output is encoded as `ISO-8859-1` instead of `UTF-8`.

I think that fixing this bug is as simple as adding a `, "UTF-8"` parameter in the call to the `OutputStreamWriter` in https://github.com/lightbend/paradox/blob/master/core/src/main/scala/com/lightbend/paradox/template/PageTemplate.scala#L43.

We are currently unable to use `sbt-site` with `paradox` due to this issue, so a release would be greatly appreciated.

Thank you!

**Comment by raboof** [comment]
Sounds like a great improvement! A PR would make that even more quick to adopt but I'll give it a go now :smile:

**Comment by ennru** [comment]
This was solved with #307.
