### ISSUE TITLE
Disable pegdown HARDWRAPS option by default

### ISSUE THREAD

**Issue by jrudolph** [lightbend/paradox#31]
Paradox seems to add the HARDWRAPS option to pegdown (by using `Extensions.ALL` as the default in the `Reader` constructor) which will introduce line breaks (`<br/>`) for each line break in the source.

This is a behavior that was introduced in Github and which may make sense if input is mainly entered through text input fields that automatically wrap long lines. However, for reading text files that are usually manually wrapped it makes more sense to join lines as intended by the original markdown definition.

See https://github.com/akka/akka-http/issues/382 as an example where hard-wraps where unexpected.

**Comment by eed3si9n** [comment]
I agree.

**Comment by jrudolph** [comment]
Is there a release planned any time soon? We are currently working on releasing akka-http whose docs are now based on paradox and it would be cool if we could generate the docs with the fixed paradox.

**Comment by ktoso** [comment]
Great to see this merged, thanks @eed3si9n.
A release would help us with this-week's Akka HTTP release, thanks in advance

**Comment by eed3si9n** [comment]
Releasing 0.2.3 now.

**Comment by jrudolph** [comment]
Yay :+1:

**Comment by eed3si9n** [comment]
https://oss.sonatype.org/content/repositories/public/com/lightbend/paradox/paradox_2.10/0.2.3/
https://bintray.com/sbt/sbt-plugin-releases/sbt-paradox/0.2.3#files/com.lightbend.paradox
It should sync to Maven Central soon.
