### ISSUE TITLE
Release: 0.6.0?

### ISSUE THREAD

**Issue by raboof** [lightbend/paradox#330]
When #329 is merged I'd say it's high time for a new release.

Since there's a lot more validations that will force people to make changes I'd say that should be 0.6.0?

**Comment by 2m** [comment]
Sounds good!

**Comment by pvlugter** [comment]
Merged. New 0.6.0 release sounds good to me too.

**Comment by pvlugter** [comment]
Created the release tag: https://github.com/lightbend/paradox/releases/tag/v0.6.0
