### ISSUE TITLE
How to use it in projects built with Maven？

### ISSUE THREAD

**Issue by GeTOUO** [lightbend/paradox#338]
How to use it in projects built with Maven？

My project used Scala built by maven. I wanted to use this library to generate documents, but I didn't find a case in maven.

**Comment by raboof** [comment]
Paradox is currently only available as an sbt plugin.

I'm not sure we'd want to also maintain a Maven plugin, but perhaps one could be built on top of the paradox_2.12 artifact. We would of course happily link to such a project.

**Comment by GeTOUO** [comment]
Okay, thank you. Hope to have a Maven plugin
