### ISSUE TITLE
Customize how newlines are rendered

### ISSUE THREAD

**Issue by evacchi** [lightbend/paradox#38]
Currently newlines introduce `<br>`s. Is it possible to customize it/make it follow [basic MD behavior](https://daringfireball.net/projects/markdown/syntax#p), i.e., hard breaks are inserted only when the line terminates with >2 spaces ?

**Comment by dwijnand** [comment]
Duplicate of #31

**Comment by eed3si9n** [comment]
There is a version with the fix, but it's buggy so let me push another release out with more fixes.

**Comment by evacchi** [comment]
sure, thanks!
