### ISSUE TITLE
Add support for @ref with fragment

### ISSUE THREAD

**Issue by sirthias** [lightbend/paradox#40]
E.g.

    @ref:[Mailing List](../support.md#mailing-list)

**Comment by gsechaud** [comment]
Could it be related to https://github.com/lightbend/paradox/pull/34?

If yes, the latest version (0.2.5) of paradox should work.

**Comment by sirthias** [comment]
Yes, I can confirm that version 0.2.5 does support @ref links with fragments.
Thanks!
