### ISSUE TITLE
Warn about scala binary version suffix on dependencies

### ISSUE THREAD

**Issue by ignasi35** [lightbend/paradox#426]
The [`@@dependency`](https://developer.lightbend.com/docs/paradox/current/directives/dependencies.html) directive renders `sbt`/Maven/Gradle/... snippets to easily copy paste a library dependency on the users build code.

The dependencies usually include a `scala.binary.version` suffix which can lead users unfamiliar with the scala ecosystem to mixing artifacts such as `akka-actor_2.13` and `akka-testkit_2.12` which leads to obscure errors (e.g. `noclassdeffounderror scala/serializable`).  

The `@@dependency` could, instead, not set the `scala.binary.version` to a given value and use a build-specific placeholder (e.g. Maven `property`) with a small comment similar to the support to [symbol/value](https://raw.githubusercontent.com/akka/alpakka-kafka/master/docs/src/main/paradox/testing.md) in:

```
@@dependency [Maven,sbt,Gradle] {
  group=com.typesafe.akka
  artifact=akka-stream-kafka-testkit_$scala.binary.version$
  version=$project.version$
  scope=test
  symbol2=AkkaVersion
  value2="$akka.version$"
  group2=com.typesafe.akka
  artifact2=akka-stream-testkit_$scala.binary.version$
  version2=AkkaVersion
  scope2=test
}
```

[rendering](https://doc.akka.io/docs/alpakka-kafka/current/testing.html#testing) as

```xml
    <properties>
      <akka.version>2.5.23</akka.version>
    </properties>
    <dependency>
      <groupId>com.typesafe.akka</groupId>
      <artifactId>akka-stream-kafka-testkit_2.12</artifactId>
      <version>2.0.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.typesafe.akka</groupId>
      <artifactId>akka-stream-testkit_2.12</artifactId>
      <version>${akka.version}</version>
      <scope>test</scope>
    </dependency>
```

But such that any paradox user gets the symbol/value usage out fo the box (instead fo copy/pasting it every single time).

This came up during a [gitter discussion](https://gitter.im/akka/akka?at=5e8c822c9316f34b8d870ed3).

So, a paradox user simply adding:

```
@@dependency [Maven,sbt,Gradle] {
  group=com.typesafe.akka
  artifact=akka-stream-kafka-testkit_$scala.binary.version$
  version=$project.version$
  scope=test
}
```

would get the following maven snippet for free:

```xml
    <properties>
      <scala.binary.version>2.5.23</scala.binary.version>
    </properties>
    <dependency>
      <groupId>com.typesafe.akka</groupId>
      <artifactId>akka-stream-kafka-testkit_${scala.binary.version}</artifactId>
      <version>2.0.2</version>
      <scope>test</scope>
    </dependency>
```

Optionally with a comment:

```xml
    <properties>
      <!-- All your artifacts must be compiled to the same scala.binary.version  (TODO: adda  link here to some relevant documentation in scala-lang.org ?)-->
      <scala.binary.version>2.5.23</scala.binary.version>
    </properties>
```

**Comment by ignasi35** [comment]
Note: this improvement is particularly useful for Java users unfamiliar with the scala ecosystem.

**Comment by ennru** [comment]
I looked into this. My plan would be to enable this automatically as soon as an artefact name uses `$scala.binary.version$`.

**Comment by ennru** [comment]
What I have now creates eg.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/458526/79432568-496a9880-7fcc-11ea-8b96-d63db13f05c1.png">

and

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/458526/79432629-6010ef80-7fcc-11ea-9d38-545070ebb1d4.png">

Without any change in the project itself. The directive detects the use of `$scala.binary.version$` and makes this happen.

Is that what you envisioned, @ignasi35 ?

**Comment by ignasi35** [comment]
Yes so much!

Thanks @ennru :-)
