### ISSUE TITLE
Consistently render content inside @@@ directives

### ISSUE THREAD

**Issue by jonas** [lightbend/paradox#49]
As noted here: akka/akka-http@f349d908d114b8d42b1287be662a26b362ef4d8c

>  There's a strange thing with how the Pegdown parser handles content
    inside a container directives (`@@@`) where it will honour the new lines
    if there's no empty line between the directive marker and the first
    text.

It would be nice if Paradox would render
```
@@@ note
A
B
@@@
```
and
```
@@@ note

A
B

@@@
```
in the same way.

**Comment by eed3si9n** [comment]
Is there an analogous markup or situation in normal markdown that we can follow?

**Comment by jonas** [comment]
Nothing comes to mind.

**Comment by eed3si9n** [comment]
How about GFM's fensed code block (```). 

```

foo

```

vs

```
foo
```

**Comment by jonas** [comment]
That would be less GitHub friendly with links etc not being rendered. If this cannot easily be fixed in PegDown I suggest to just document it.

**Comment by eed3si9n** [comment]
So what's the situation with `@@@ note`?
Does it add extra spaces on top and bottom?

**Comment by jonas** [comment]
No, it didn't. Fixed it in the parse.
