### ISSUE TITLE
Java 16 support

### ISSUE THREAD

**Issue by LeifW** [lightbend/paradox#491]
Fails on Java 16 with `java.lang.reflect.InaccessibleObjectException` because the "illegal reflective access" warning triggered by parboiled on earlier JVMs is now an error.
See https://github.com/sirthias/parboiled/issues/175
and https://github.com/sirthias/parboiled/issues/128

**Comment by nafg** [comment]
Workaround is to pass `--add-opens java.base/java.lang=ALL-UNNAMED`

**Comment by raboof** [comment]
updating to parboiled 1.4.1, which should work with newer JDK versions without having to explicitly open up modules (though this does mean we don't support Java 8 anymore)

**Comment by SethTisue** [comment]
minimum version with the fix is https://github.com/lightbend/paradox/releases/tag/v0.10.0
