### ISSUE TITLE
Migrate from scalariform to scalafmt

### ISSUE THREAD

**Issue by mdedetrich** [lightbend/paradox#515]
I noticed that this project is still using scalariform which is no longer maintained (see last commit at https://github.com/scala-ide/scalariform). Instead the community has moved to scalafmt (which newer akka/lightbend projects are using anyways).

The only issues with doing such a change is it creates a huge diff however since there are not any notable pull requests that are open (apart from https://github.com/lightbend/paradox/pull/431 which is approved but not merged yet, also https://github.com/lightbend/paradox/pull/514 but this is not a feature and hence can easily be merged beforehand).

**Comment by pvlugter** [comment]
Good idea. Maybe a scalafmt config that's fairly aligned with what Akka is using.

**Comment by mdedetrich** [comment]
I was thinking of using the one from sbt-paradox-project-info where I already added scalafmt (https://github.com/lightbend/sbt-paradox-project-info/blob/master/.scalafmt.conf). I also added that same configuration in another couple of lightbend projects, are you happy with that one?

Also should I wait for https://github.com/lightbend/paradox/pull/431 or should I go ahead right now?

**Comment by pvlugter** [comment]
Ok, sounds good. Anything that looks reasonable works.

Looks like #431 will need some conflicts resolved already. But probably best to merge that first. It's been sitting there for a while.

**Comment by mdedetrich** [comment]
Cool I have subscribed to that PR so I will get notified when it gets merged
