### ISSUE TITLE
Doc validation

### ISSUE THREAD

**Issue by jroper** [lightbend/paradox#53]
The paradox sbt plugin should provide a task for validating docs.  This should include:

* Missing links tests
* Missing fragment links tests
* Missing scaladoc/javadoc links tests
* Missing scaladoc/javadoc fragment (ie, to specific methods/fields) links tests
* Missing code snippets tests
* Missing resources (eg, inline image links, etc) tests

An additional task should be provided that checks for dead external links - this should be an additional task, since a task that calls out to many external websites will cause problems if run from CI, both in terms of false negatives and also it's not playing nicely on the web.  Instead the intent would be to run this task manually every so often.

**Comment by jonas** [comment]
For linking between Paradox sites, I suggest we consider packaging docs in JARs (which might already be the case for tech hub) so that this can be managed partially via dependencies. Checking links would be a matter of reading a manifest file which lists all pages and page anchors.

This would also allow downstream projects to provide Paradox properties such as where the Paradox site is hosted and Scaladoc/Javadoc base URLs.

**Comment by benmccann** [comment]
This functionality can be found in [LightbendMarkdownValidation](https://github.com/typesafehub/lightbend-markdown/blob/master/plugin/src/main/scala/com/lightbend/markdown/sbt/LightbendMarkdownValidation.scala) and [PlayDocsValidation](https://github.com/playframework/playframework/blob/master/framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala), so we can use those as a starting point. This is a pre-requisite for Play and/or Lagom moving to Paradox one day. The validation on Play and Lagom's docs catches a lot of errors during development.

**Comment by 2m** [comment]
Links to scaladoc with fragment syntax can be checked by sbt-sdlc: https://github.com/sbt/sbt-sdlc

**Comment by jroper** [comment]
Validation for links to any assets that are available to the build (could include images, api docs, etc) has been implemented in #359, additionally that PR also allows optionally validating external links by making HTTP requests on them. I think this validation, in combination with the validation that paradox already offered as part of the compile task, gives all the functionality that I was hoping for (and more).

Validation of links across sites as described by @jonas is possible in certain scenarios, such as if the links use absolute URLs (eg provided by a configure extref) then they can be validated using the external links validation task. Also, if the two sites are hosted on the same host with relative links to each other, then if they publish their docs in an artifact that each other can depend on, they can both pull in the others artifact, extract it, and add the contents as mappings to the validation task. Of course, if the links went both ways across the projects, there would be a circular dependency that could cause problems sometimes, but otherwise it'd work fine.

So once #359 is merged, I think we can close this.

**Comment by pvlugter** [comment]
Closing now that #359 is merged and released in paradox 0.6.5.

**Comment by pvlugter** [comment]
> For linking between Paradox sites, I suggest we consider packaging docs in JARs (which might already be the case for tech hub) so that this can be managed partially via dependencies. Checking links would be a matter of reading a manifest file which lists all pages and page anchors.

For interest: the "paradox" name originally came from the idea of packaging docs in jars and publishing alongside modules to be assembled together (which we started with playdoc), with "para-" meaning "beside" or "adjacent to" docs.

**Comment by jroper** [comment]
Thanks for the release!
