### ISSUE TITLE
Error creating extended parser class

### ISSUE THREAD

**Issue by patriknw** [lightbend/paradox#536]
Fails with this error when using JDK 17. Works with 11.

```
Error creating extended parser class: Could not determine whether class 'org.pegdown.ParserWithDirectives$$parboiled' has already been loaded
```

I don't expect it to be fixed anytime soon but creating issue in case it can help others running into the same problem.

**Comment by pvlugter** [comment]
Which paradox version? Paradox 0.10 should support JDK 17. Parboiled bumped in #526 for this.

**Comment by patriknw** [comment]
Thanks, it was on older Paradox. Works fine with latest.
