### ISSUE TITLE
Provide support for origin source URLs

### ISSUE THREAD

**Issue by jroper** [lightbend/paradox#57]
Lagom (and several other projects) render links back to the original markdown source files in GitHub to facilitate user contributions, see the bottom of this page for an example:

http://www.lagomframework.com/documentation/1.2.x/java/WhatDoesLagomMean.html

Paradox needs to support this such that a theme can render that link.

**Comment by dwijnand** [comment]
I believe this to be incredibly useful and should definitely support it sooner rather than later.

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/lightbend/paradox/pull/69
