### ISSUE TITLE
Support linking to the new scaladoc

### ISSUE THREAD

**Issue by 2m** [lightbend/paradox#61]
Linking to the 2.12 style scaladoc does not work. New scaladoc does have frames and does not suport `#akka.stream....` at the end of the links. For the new scaladoc the url should be

`http://developer.lightbend.com/docs/api/alpakka/latest/akka/stream/alpakka/amqp/QueueDeclaration.html`

instead of

`http://developer.lightbend.com/docs/api/alpakka/latest/#akka.stream.alpakka.amqp.QueueDeclaration`

This could be implemented as a new directive (e.g. `@nscaladoc`, for new scaladoc).

Or we could make the current `@scaladoc` directive smarter to automatically determine if there is old or new sclaladoc at the end of the link. Could be a foundation for (or result of) #53.

**Comment by jonas** [comment]
I have proposed a fix as part of the javadoc directive PR see https://github.com/lightbend/paradox/pull/52/commits/f9b12b2a7a77f76a6e2c9cc608c35ba84abd0a5c

**Comment by jonas** [comment]
This was fixed by #52

**Comment by ktoso** [comment]
Excellent, thanks! :-)

**Comment by ktoso** [comment]
(Meh, i don't have close rights on this repo)
