### ISSUE TITLE
Tab selection preference should be remembered in a cookie

### ISSUE THREAD

**Issue by ktoso** [lightbend/paradox#63]
Depends on https://github.com/lightbend/paradox/issues/11 (about switching all tabs)

If I'm a Java or Scala person, I always want to go to a page and keep seeing the Java (or Scala) snippets, so I don't get angry about clicking those tabs all the time ;-)

Very important feature to not make users angry about the tabs IMO.

**Comment by ktoso** [comment]
This is rather important if Akka HTTP is to move to a "single tree", which I think would improve status quo a lot, people would have an easier time contributing.

**Comment by pvlugter** [comment]
Fixed in #107
