### ISSUE TITLE
Open in browser via sbt command?

### ISSUE THREAD

**Issue by analytically** [lightbend/paradox#71]
How would the paradox sbt plugin be able to do:

```
  dependencyBrowseGraph <<= (dependencyBrowseGraphHTML, streams).map { (uri, streams) ⇒
      streams.log.info("Opening in browser...")
      java.awt.Desktop.getDesktop.browse(uri)
      uri
    },
```
https://github.com/jrudolph/sbt-dependency-graph/blob/master/src/main/scala/net/virtualvoid/sbt/graph/DependencyGraphSettings.scala#L84

**Comment by dwijnand** [comment]
For anything that isn't specific to paradox we've being deferring it to sbt-site, which generalises on site generation capabilities, such as preview support: https://github.com/sbt/sbt-site/pull/73

**Comment by analytically** [comment]
This should be simple enough to add to paradox directly as well no?

**Comment by jonas** [comment]
Try:

```sbt
run := {
  val url = (paradox in Compile).value / "index.html"
  streams.value.log.info(s"Opening $url in browser...")
  java.awt.Desktop.getDesktop.browse(url.toURI)
}
```

**Comment by ennru** [comment]
Fixed with https://github.com/lightbend/paradox/issues/193
