### ISSUE TITLE
How to insert variable in link?

### ISSUE THREAD

**Issue by Sciss** [lightbend/paradox#76]
For example, I have the following in a markdown document:

    - [All Platforms](https://github.com/Sciss/ScalaColliderSwing/releases/download/v@var:[scalacollider-swing.version]/scalacolliderswing-@var:[scalacollider-swing.version]-universal.zip)

And in `build.sbt`:

    paradoxProperties in Compile +=
      "scalacollider-swing.version" -> "1.32.0"

I'm expecting the link to be resolved as

    - [All Platforms](https://github.com/Sciss/ScalaColliderSwing/releases/download/v1.32.0/scalacolliderswing-1.32.0-universal.zip)

before rendering. Can this be done?

**Comment by jonas** [comment]
In order for the links to work for each release they should point to the
API docs of a specific version. The easiest way to do this will probably be
to use the `@scaladoc` and `@javadoc` directives as documented here
http://developer.lightbend.com/docs/paradox/latest/features/linking.html#scaladoc-directive
.

This will require that the Paradox plugin is bumped to version 0.2.7.

**Comment by Sciss** [comment]
No, this is a download link, nothing to do with API docs... I need to be able to paste a variable into the link.

**Comment by Sciss** [comment]
Also in regular text, it doesn't pick up my variable:

```scala
val root = (project in file("."))
  .enablePlugins(ParadoxSitePlugin, SiteScaladocPlugin)
  .settings(
    ...
    paradoxProperties in Compile ++= Map(
      "swingversion" -> "1.32.0"
    )
  )
```

In markdown:

```md
@@@vars
To start hacking straight away, download the latest version $swingversion$ of ScalaCollider-Swing:
@@@
```

This should work, no? It simply leaves `$swingversion$` in the rendered HTML.

**Comment by jonas** [comment]
Oops sorry replied to the wrong email. Take a look at `@extref` http://developer.lightbend.com/docs/paradox/latest/features/linking.html#extref-directive

You can define a link prefix in you build.sbt and use that in the markdown file.

**Comment by Sciss** [comment]
I'm having a general problem with the properties it seems. None of them work. Like 

    FOO @extref[RFC 2119](rfc:2119) BAR

is rendered as

    FOO BAR

with nothing in between. There are no warnings or error messages. I did add this

    "extref.rfc.base_url" -> "http://HELLO.ietf.org/html/rfc%s"

Just is not found (this would explain why `$swingversion$` is also not found.

**Comment by jonas** [comment]
With this in `build.sbt`:
```sbt
val docs = project.in(...)
  .settings(
    paradoxProperties in Compile ++= Map(
      "extref.download.base_url" -> s"https://github.com/Sciss/ScalaColliderSwing/releases/download/v${version.value}/scalacolliderswing-${version.value}-%s.zip"
    )
  )
```
the following should work:
```markdown
- @extref[All Platforms](download:universal)
```
If the RFC example doesn't work this might be due to an issue in the sbt-site plugin.

**Comment by Sciss** [comment]
:-( Doesn't work: https://sciss.github.io/ParadoxTest/

Which plugin versions are you using? Mine: https://github.com/Sciss/ParadoxTest/blob/95dd86c6887d2ec9971184e34acc07da46c14f69/project/plugins.sbt ; build.sbt: https://github.com/Sciss/ParadoxTest/blob/95dd86c6887d2ec9971184e34acc07da46c14f69/build.sbt

**Comment by jonas** [comment]
OK, it should work when you use `paradoxProperties in Paradox`:

```
val root = (project in file("."))
  .enablePlugins(ParadoxSitePlugin, SiteScaladocPlugin)
  .settings(
    ...
    paradoxProperties in Paradox ++= Map(
      "swingversion" -> "1.32.0"
    )
  )
```

**Comment by Sciss** [comment]
Yes! Thanks again for your fast help, very much appreciated!

**Comment by jonas** [comment]
Glad we figured it out
