### ISSUE TITLE
https://github.com/typesafehub/paradox-theme-lightbend is not fould

### ISSUE THREAD

**Issue by xuwei-k** [lightbend/paradox#80]
https://github.com/lightbend/paradox/blob/3546b75342f74/docs/src/main/paradox/features/theming.md#external-theme

```
The [Lightbend theme](https://github.com/typesafehub/paradox-theme-lightbend) is a good example of what should look like a paradox theme repository.
```

**Comment by eed3si9n** [comment]
That theme is not public.
Maybe I have to make a new external theme that's public as an example.

**Comment by jonas** [comment]
I am considering porting the scala-sbt.org theme to paradox as part of sbt/sbt-site#84. Just need to figure out a way to package it.

Dreaming up stuff it would be nice to provide the [read the docs](https://github.com/snide/sphinx_rtd_theme) theme and I'd also personally be interested in a Material Design based theme like http://squidfunk.github.io/mkdocs-material/

**Comment by eed3si9n** [comment]
scala-sbt.org's theme is actually pretty outdated since it's based on the color scheme of Typesafe, and is subject to change in the future.
I was going to make a variant of Generic theme with Monokai code formatting or something.
