### ISSUE TITLE
Unclear where custom template should reside

### ISSUE THREAD

**Issue by Sciss** [lightbend/paradox#89]
The documentation on the page http://developer.lightbend.com/docs/paradox/latest/features/theming.html#create-local-templates is not working. I have this `build.sbt`:

```scala
name := "Foo Bar"
scalaVersion := "2.12.1"
enablePlugins(ParadoxSitePlugin)
paradoxTheme := None
```

But when I run `sbt previewSite`, it doesn't find the template:

```
java.lang.RuntimeException: StringTemplate 'page' was not found for '/home/hhrutz/IEM/Projektantraege2014/website/target/paradox/paradox/html/index.html'. Create a template or set a theme that contains one.
	at scala.sys.package$.error(package.scala:27)
	at com.lightbend.paradox.template.PageTemplate.write(PageTemplateSystem.scala:55)
```

I have copied the generic theme:

```
$ ls -la src/main/paradox/_template/
total 48
drwxr-xr-x 4 hhrutz hhrutz  4096 Jan 30 16:25 .
drwxr-xr-x 3 hhrutz hhrutz  4096 Jan 30 16:28 ..
drwxr-xr-x 3 hhrutz hhrutz  4096 Jan 30 16:20 css
drwxr-xr-x 2 hhrutz hhrutz  4096 Jan 30 16:20 js
-rw-r--r-- 1 hhrutz hhrutz   622 Jan 30 16:20 menu.st
-rw-r--r-- 1 hhrutz hhrutz   298 Jan 30 16:25 navigation.st
-rw-r--r-- 1 hhrutz hhrutz  3990 Jan 30 16:20 page.st
-rw-r--r-- 1 hhrutz hhrutz   145 Jan 30 16:20 source.st
-rw-r--r-- 1 hhrutz hhrutz    42 Jan 30 16:20 title.st
```

**Comment by Sciss** [comment]
I have also moved `_template` into `src/paradox/` instead of `src/main/paradox` (as this seems to be the required location for the markdown files), but the error is the same.

**Comment by Sciss** [comment]
I managed to get it working by the wonders of sbt -- using `val root = project.in(file("."))` instead of "flat" sbt style (this seems to be related to the confusion between `src/paradox` and `src/main/paradox`, and using just the `ParadoxPlugin` instead of `ParadoxSitePlugin`. So it seems the latter has a problem.

**Comment by jonas** [comment]
Can this be closed? From my understanding you ended up putting the files in
src/paradox as expected by sbt-site. The last comment seems to be related
with the fact that template files are not automatically reloaded by the sbt
plugin, for which you created another issue.

**Comment by Sciss** [comment]
I still can't use `ParadoxSitePlugin`, so I just use `ParadoxPlugin`. I don't understand why the former doesn't use the same paths as the latter.

**Comment by jonas** [comment]
OK, I'll try to reproduce.

Using paradox in conjunction with sbt-site is documented here: http://www.scala-sbt.org/sbt-site/generators/paradox.html. Right now it is very basic and might need some improvements.

**Comment by Sciss** [comment]
Oh ok, I see, `ParadoxSitePlugin` uses `src/paradox` instead of `src/main/paradox`, but now it doesn't pick up `paradoxProperties`. So these are other problems now, closing the issue.

**Comment by jonas** [comment]
Yes, `paradoxProperties` has to be scoped using `Paradox` instead of `Compile` with the sbt-site plugin:

```sbt
paradoxProperties in Paradox ++= Map(
  "extref.rfc.base_url" -> "http://tools.ietf.org/html/rfc%s"
)
```
