### ISSUE TITLE
Feature: support `sbt ~paradox`

### ISSUE THREAD

**Issue by Sciss** [lightbend/paradox#91]
It would be great if paradox could track the source files (custom template, input markdown etc.) and automatically re-render when running as `sbt ~paradox` and one edits a file, e.g. `page.st`.

**Comment by JohnMurray** [comment]
This is currently working for me for the input markdown. I can't speak to the custom template since I'm not using one ATM.

**Comment by Sciss** [comment]
Yes, sorry, I think this was just for tuning the css files, the markdown files are traced indeed.

**Comment by pvlugter** [comment]
Should be fixed in #108. Available in paradox 0.2.11.
