### ISSUE TITLE
Making "figures" (e.g. images with caption and wide as text box)

### ISSUE THREAD

**Issue by Sciss** [lightbend/paradox#94]
Sorry that I'm using the GitHub issues for all this, I don't know if there is any other channel (Gitter, mailing list, ...) to ask questions?

I would like to know what the recommended way is to embed images in the markdown files with particular constraints; for instance, I want an image to have the same width as the text box, in other words I somehow need to qualify the CSS, probably best through a class id. Can I do this with the GH flavoured markdown? Should I just insert a `<IMG>`? (This is a bit ugly because I don't get to use the relative URL syntax).

This question extends to other things as well, such as embedding video or sound file. I guess I'm stretching the scenario here beyond what Paradox was made for initially, as I'm trying to build a project website that I would otherwise do with Jekyll -- but now I really like Paradox, it's small, clean, and _fast_, and I don't have to deal with Ruby things. So I'm hoping I can do all these somehow.

**Comment by Sciss** [comment]
> I'm trying to build a project website that I would otherwise do with Jekyll

By the way, here is the initial result: http://almat.iem.at/ - thanks so much for Paradox, it was easy enough to get this done in no time. Feeding the different colour scheme into the CSS was a bit of search and replace, and so I wished there was also a templating for CSS, like macros for defining base colours, deriving brighter, darker, less saturated etc. colours; my last Jekyll project had that, I don't know what system it used (is it SASS?), that was really nice. Are you planning something like this, as an optional pre-processing hook?

**Comment by jonas** [comment]
@Sciss That looks great!

Regarding images and styling the `@@@div` container along with the markdown image syntax would be one way to control the size and layout. Images URLs can be relative as long as you put the images inside the Paradox source directory.

For more advanced media you have the option to create your own custom directives. Akka HTTP's [`@signature`](https://github.com/akka/akka-http/blob/v10.0.3/project/ParadoxSignatureDirective.scala) is one example and #35 will make this easier.

For theming I think it would be great if Paradox adopted some sort of convention making it easy to customize the theme by including a CSS file by defining a `paradoxProperties`, i.e. `"theme.custom.css" -> "path/to/file.css"` (and similarly for JavaScript). CSS pre-processing tools should be possible given that Paradox's sbt theme plugin uses `sbt-web` but I didn't personally play with that.

**Comment by Sciss** [comment]
Ok thanks, I'll looking into the `@signature` example. Wrapping in `@@@div` makes it possible to add specific CSS for figure images, you are right. Closing for now.
